repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: trailing-whitespace
  - id: flake8
  - id: check-yaml
- repo: https://github.com/codespell-project/codespell
  rev: v1.15.0
  hooks:
  - id: codespell

# black requires py3.6+
#- repo: https://github.com/python/black
#  rev: 19.3b0
#  hooks:
#  - id: black
#    language_version: python3
#- repo: https://github.com/asottile/blacken-docs
#  rev: v1.0.0-1
#  hooks:
#  - id: blacken-docs
#    additional_dependencies: [black==19.3b0]
